apiVersion: v2
name: mongo-42
description: MongoDB version 4.2 with NetApp persistent storage
type: application
version: 1.0.2
appVersion: "4.2.3"
icon: https://media.mongodb.org/ico/icon-leaf.png
maintainers:
  - name: Platforms Group
    url: https://www.olcf.ornl.gov/about-olcf/staff-sections/operations/platforms/
