apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: {{ include "mongo-42.fullname" . }}
  labels:
    {{- include "mongo-42.labels" . | nindent 4 }}
spec:
  version: {{ .Chart.AppVersion | quote }}
  {{- if .Values.mongodb.spec.authSecret }}
  authSecret:
      name: {{ .Values.mongodb.spec.authSecret }}
{{- end }}
  storageType: Durable
  storage:
    storageClassName: "netapp-nfs"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mongodb.spec.storage.size | quote }}
  sslMode: disabled
  podTemplate:
    spec:
      resources:
        {{- toYaml .Values.mongodb.spec.resources | nindent 8 }}
  terminationPolicy: WipeOut
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-{{ include "mongo-42.fullname" . }}-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "mongo-42.fullname" . }}
  ingress:
    - {}
  policyTypes:
  - Ingress
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "mongo-42.fullname" . }}
  name: {{ include "mongo-42.fullname" . }}
spec:
  ports:
  - name: mongod
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: {{ include "mongo-42.fullname" . }}
  type: ClusterIP
