{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "minio-nfs.fullname" . }}
spec:
{{- if .Values.route.hostname }}
  host: {{ .Values.route.hostname }}
{{- end }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "minio-nfs.fullname" . }}
{{- end }}
