apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-nfs.fullname" . }}
  labels:
    app: {{ template "minio-nfs.name" . }}
    chart: {{ template "minio-nfs.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- include "minio-nfs.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- if (or (eq .Values.service.type "ClusterIP" "") (empty .Values.service.type)) }}
  type: ClusterIP
{{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
{{- else }}
  type: {{ .Values.service.type }}
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 9000
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- range $i , $ip := .Values.service.externalIPs }}
  - {{ $ip }}
{{- end }}
{{- end }}
  selector:
    app: {{ template "minio-nfs.name" . }}
    release: {{ .Release.Name }}
