replicaCount: 1

image: nginx
imagePullPolicy: IfNotPresent
# imagePullSecrets: []

podAnnotations: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  external: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  host: ""

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

volumes: []