apiVersion: kubedb.com/v1alpha2
kind: Redis
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  # mode: Cluster
  # cluster:
  #   master: 3
  #   replicas: 1
  version: {{ .Values.version | quote }}

  serviceTemplates:
    - alias: primary
      spec:
        type: {{ .Values.serviceTemplates.primary.type }}

  storageType: Durable
  storage:
    storageClassName: {{ .Values.storage.class | quote }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.storage.size | quote }}

  podTemplate:
    spec:
      resources:
        {{- toYaml .Values.resources | nindent 8 }}
