apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: {{ include "mysql-57.fullname" . }}
  labels:
    {{- include "mysql-57.labels" . | nindent 4 }}
spec:
  version: {{ .Chart.AppVersion | quote }}
{{- if .Values.mysql.spec.authSecret }}
  authSecret:
      name: {{ .Values.mysql.spec.authSecret }}
{{- end }}
  storageType: "Durable"
  storage:
    storageClassName: netapp-nfs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mysql.spec.storage.size | quote }}
{{- if .Values.mysql.spec.configMapName }}
  init:
   script:
     configMap:
       name: {{.Values.mysql.spec.configMapName }}
{{- end }}
  requireSSL: false
  # configSecret:
  #  name: my-custom-config
  #podTemplate:
  #  metadata:
  #    annotations:
  #      passMe: ToDatabasePod
  #  controller:
  #    annotations:
  #      passMe: ToStatefulSet
  #  spec:
  #    serviceAccountName: my-service-account
  #  args:
  #    - --character-set-server=utf8mb4
  #    env:
  #    - name: MYSQL_DATABASE
  #      value: myDB
  #    resources:
  #      requests:
  #        memory: "64Mi"
  #        cpu: "250m"
  #      limits:
  #        memory: "128Mi"
  #        cpu: "500m"
  #serviceTemplates:
  #- alias: primary
  #  metadata:
  #    annotations:
  #      passMe: ToService
  #  spec:
  #    type: NodePort
  #    ports:
  #    - name:  http
  #      port:  9200
  terminationPolicy: {{ .Values.mysql.spec.terminationPolicy | quote }}
