apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: {{ include "mysql-57.fullname" . }}
  labels:
    {{- include "mysql-57.labels" . | nindent 4 }}
spec:
  version: {{ .Chart.AppVersion | quote }}
{{- if .Values.mysql.spec.authSecret }}
  authSecret:
      name: {{ .Values.mysql.spec.authSecret }}
{{- end }}
  storageType: "Durable"
  storage:
    storageClassName: netapp-nfs
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mysql.spec.storage.size | quote }}
{{- if .Values.mysql.spec.configMapName }}
  init:
   script:
     configMap:
       name: {{.Values.mysql.spec.configMapName }}
{{- end }}
  requireSSL: false
  podTemplate:
    spec:
      resources:
        {{- toYaml .Values.mysql.spec.resources | nindent 8 }}
  terminationPolicy: {{ .Values.mysql.spec.terminationPolicy | quote }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-{{ include "mysql-57.fullname" . }}-access
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ include "mysql-57.fullname" . }}
  ingress:
    - {}
  policyTypes:
  - Ingress
