apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "postgresql.fullname" . }}-allow-kubedb
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: kubedb-operator
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: kubedb.com
  policyTypes:
  - Ingress
