apiVersion: v2
name: rabbitmq
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
icon: file://icon.svg
maintainers:
  - name: Platforms Group
    url: https://www.olcf.ornl.gov/about-olcf/staff-sections/operations/platforms/
dependencies:
- name: deploy-image
  version: 0.4.1
  repository: https://olcf.github.io/slate-helm-charts
