{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: "RoleBinding"
metadata:
  name: admin-role-{{ include "gitlab-runner.fullname" . }}
  labels:
    app: {{ include "gitlab-runner.fullname" . }}
    chart: {{ include "gitlab-runner.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  namespace: {{ default .Release.Namespace .Values.runners.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: "ClusterRole"
  name: admin
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: "{{ .Release.Namespace }}"
{{- end -}}
