apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "desktop-vnc.fullname" . }}
  labels:
    {{- include "desktop-vnc.labels" . | nindent 4 }}
    ccs.ornl.gov/externalRoute: 'true'
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ include "desktop-vnc.fullname" . }}
  port:
    targetPort: http
