apiVersion: v1
kind: Service
metadata:
  name: {{ include "desktop-vnc.fullname" . }}
  labels:
    {{- include "desktop-vnc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 6000
      targetPort: 6000
      protocol: TCP
      name: x11
  selector:
    {{- include "desktop-vnc.selectorLabels" . | nindent 4 }}
