apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
data:
  nginx.conf: |
    worker_processes 5;
    error_log  /var/log/nginx/error.log notice;
    pid        /tmp/nginx.pid;
    events {
    }
    http {
      proxy_temp_path /tmp/proxy_temp;
      client_body_temp_path /tmp/client_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;

      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /var/log/nginx/access.log  main;

      sendfile        on;
      #tcp_nopush     on;

      keepalive_timeout  65;

      #gzip  on;

      server {
        listen 8080;
        keepalive_timeout 5;
        location /nginx_status {
          stub_status;
          access_log off;
        }
        location / {
          root /ccs/proj/{{ include "library.project" . | lower }}/www;
        }
        location = /_healthz {
          log_not_found off; access_log off; allow all;
          add_header Content-Type text/plain;
          return 200 'ok';
        }
      }
    }