{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deploy-image.fullname" . }}
  labels:
    {{- include "deploy-image.labels" . | nindent 4 }}
spec:
  accessModes:
  {{- if contains "nfs" .Values.persistence.storageClass }}
    - ReadWriteMany
  {{- end }}
  {{- if contains "block" .Values.persistence.storageClass }}
    - ReadWriteOnce
  {{- end }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
